### ISSUE TITLE
"This plugin is available ONLY for Gradle project that use the kotlin script DSL"

### ISSUE THREAD

**Issue by mklueh** [nicolasfara/conventional-commits#125]
Hello, 
thank you for the nice plugin. I think my team will love it ;)

One question, it states that "This plugin is available ONLY for Gradle project that use the kotlin script DSL" - but it seems it also works with the standard Groovy DSL so far in our case. Are there any side-effects that happen unnoticed or is this hint obsolote?

**Comment by nicolasfara** [comment]
Hi @mklueh!
First of all, many thanks for appreciating the plugin :)

That sentence referred to an older version of the plugin. I haven't tested the plugin on Groovy, but it should work!
Please, if you find out some incompatibility or problems with groovy, feel free to open an issue or pull request :)
