### ISSUE TITLE
.git/hooks/commit-msg -> No such file or directory when running Gitlab CI pipeline

### ISSUE THREAD

**Issue by oliverkuntze** [nicolasfara/conventional-commits#170]
Hey, 

thank's for your great plugin.

It works like a charm when I push my commits to the remote repository.

However, when Gitlab CI picks up the commit and starts its pipeline(s) I get the following error:
```
Failed to notify project evaluation listener.
   > /builds/myProject/.git/hooks/commit-msg (No such file or directory)
```
and the build fails.

Do you have  any ideas what I am missing / I can do to solve this?

Cheers

Oliver

**Comment by oliverkuntze** [comment]
Is this project dead? A brief note would be highly appreciated.

Cheers 

Oliver

**Comment by nicolasfara** [comment]
Hi @oliverkuntze, sorry for the delay. I'm very busy at the moment.
Could you provide the pipeline specification?
However, the plugin creates the `.git/hooks/commit-msg` when gradle is invoked the first time. Before that moment the hook file is not created.

**Comment by oliverkuntze** [comment]
Hi @nicolasfara .
Thanks for your reply.
I am testing adding mkdir -p .git/hooks/ and optionally && touch .git/hooks/commit-msg in a before_script im my gradle based tasks atm.
Apparently resolve(".git/hooks/commit-msg") cannot create the hook file if the hooks folder is not existing.
I am not familiar with Kotlin. Does resolve autocreate missing folders? If not, it would be great if you could add that to your plugin.
Cheers
Oliver

**Comment by oliverkuntze** [comment]
Adding mkdir -p .git/hooks/ does the trick. However hooks are not executed when merging in Gitlab. But your builds will at least execute.

**Comment by nicolasfara** [comment]
> Hi @nicolasfara . Thanks for your reply. I am testing adding mkdir -p .git/hooks/ and optionally && touch .git/hooks/commit-msg in a before_script im my gradle based tasks atm. Apparently resolve(".git/hooks/commit-msg") cannot create the hook file if the hooks folder is not existing. I am not familiar with Kotlin. Does resolve autocreate missing folders? If not, it would be great if you could add that to your plugin. Cheers Oliver

I don't know the GitLab workflow model, but from what you say, I suppose the repository is not cloned in the runner but simply copied? Because if the repo is cloned, git creates the `.git` folder with the samples hooks.
I can fix this issue in two ways:
  1. Raise a warning if the `.git/hooks` folder is missing
  2. Create the `.git/hooks/commit-msg` file manually even if no git repo is configured in CI

Let me know, in your opinion, which is the best option for this kind of scenario.

**Comment by oliverkuntze** [comment]
Hi @nicolasfara .
Yes, to speed things up, Gitlab fetches a shallow copy of the git repo.
The .git folder is there. And so are several subfolders inside it.
No" hooks" folder is created this way.
I would suggest to add the creation of the hook folder if it is missing. Right before it.resolve(".git/hooks/commit-msg").writeScript(scriptContent) in ConventionalCommitScript.kt.
Cheers 
Oliver
