### ISSUE TITLE
Output color don't seem to work `macOS`

### ISSUE THREAD

**Issue by ennioVisco** [nicolasfara/conventional-commits#199]
A picture to show the issue currently observed on command line on Mac.
<img width="675" alt="image" src="https://github.com/nicolasfara/conventional-commits/assets/740025/c962aadf-8421-482e-bfad-2dc0445c668e">

**Comment by nicolasfara** [comment]
Hi @ennioVisco,
sorry for the delay. I'm swamped at the moment.
For this reason, it's likely I will take some time to fix the issue even because I don't have a macOS machine.
A PR fixing this issue is welcome otherwise, I will try to my best in the next weeks  :)

**Comment by sschuberth** [comment]
Just FYI, for color output in general I can recommend https://github.com/ajalt/mordant.

**Comment by nicolasfara** [comment]
I tried to fix the issue with the tip from @sschuberth (thank you!)
Feel free to reopen the issue if any other related problems arise.
The new version should be available in minutes.

**Comment by sschuberth** [comment]
> I tried to fix the issue with the tip from @sschuberth (thank you!)

You're welcome, though I'm not 100% certain whether [your code](https://github.com/nicolasfara/conventional-commits/commit/e544840c32118ec8bb6069cbe597526d1d3d2179) will as work as expected. I thought rendering with Mordant also requires the use of a `Terminal()` instance to print to, but I might be mistaken.

**Comment by nicolasfara** [comment]
@sschuberth Based on my test it works also without `Terminal`
Remember that the check will be performed on a bash script since git uses it for hooks, so the check is not performed by the gradle task.
If you run from the IDE the tests, you will see the colored output.
Let me know if you encounter other problems :)

**Comment by ennioVisco** [comment]
@nicolasfara almost there, one is working, the other is not: 
<img width="602" alt="image" src="https://github.com/nicolasfara/conventional-commits/assets/740025/3daf4733-3e9f-4724-bb49-fcffac55c628">

**Comment by nicolasfara** [comment]
> @nicolasfara almost there, one is working, the other is not: <img alt="image" width="602" src="https://user-images.githubusercontent.com/740025/263833363-3daf4733-3e9f-4724-bb49-fcffac55c628.png">

Hi @ennioVisco
In the example message, there is no colored output.
The `\x27` is the apostrophe symbol that is not rendered correctly in your terminal.
I'll publish a fix removing that since they are not releveant
