### ISSUE TITLE
Can't configure plugin with Groovy

### ISSUE THREAD

**Issue by nigelsim** [nicolasfara/conventional-commits#49]
The plugin works OK when there is no configuration, but when I add the following to `build.gradle` it errors out

```
conventionalCommits {   
    setupScript()
}
```

Error

```
> No signature of method: build_89vvqvzslvcqadva76yqxyosa.conventionalCommits() is applicable for argument types: (build_89vvqvzslvcqadva76yqxyosa$_run_closure18) values: [build_89vvqvzslvcqadva76yqxyosa$_run_closure18@6c23c245]
```

**Comment by nicolasfara** [comment]
Hi @nigelsim thanks for reporting the error.
I will investigate your error ASAP :)

**Comment by nicolasfara** [comment]
Hi @nigelsim the problem you raised is due the groovy DSL. The plugin is written in Kotlin and this generate incompatibility with groovy. At this time there's no intention to enable compatibility with groovy, but if you want to contribute adding groovy compatibility (I don't know how, I'm not an expert at all of groovy), PRs are welcome :)

I'll update the readme saying groovy syntax is no supported

**Comment by nigelsim** [comment]
Trying to reproduce now, I have some issues, but not the one listed here. For documentation sake, here is what I've found.

The following should work:

```groovy
conventionalCommits {   
    setupScript()
}
```

This won't work:

```groovy
conventionalCommits {
    from {'echo test'}
    setupScript()
}
```

But this will:

```groovy
conventionalCommits {
    from('#!/bin/bash') {'echo test'}
    setupScript()
}
```

This also won't work as the internal Kotlin `URL` class is used:

```groovy 
conventionalCommits {
    from(URL("https://example.com/commit-msg.sh"))
    setupScript()
}
```

This may be a suitable workaround. Having a blank shebang just omits that line, so the URL content is all that is used in the file:

```groovy
conventionalCommits {
    from("", { new URL("https://example.com/commit-msg.sh").getText() })
    setupScript()
}
```

For my purposes I have the file in the repo, so I just want to copy it into place:

```groovy
conventionalCommits {
    from("", { new File("utils/commit-msg").text })
    setupScript()
}
```
